# Generated by Django 3.2.8 on 2021-10-28 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0002_category_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
