# Generated by Django 3.2.8 on 2021-11-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0003_auto_20211028_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
